name: 'actions-environment-variables'
description: ''
inputs:
  branch:
    required: true
    default: ''
  gitToken:
    required: true
    default: ''
  vars:
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
