name: 'actions-set-environment'
description: ''
inputs:
  env:
    required: false
    default: ''
  secrets:
    required: false  
  branch:
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
