name: 'actions-set-environment'
description: ''
inputs:
  env:
    required: false
    default: ''
  secrets:
    required: false  
  branch:
    required: true
    default: ''
  role-to-assume:
    required: true
    default: ''
  aws-access-key-id:
    required: true
    default: ''
  aws-secret-access-key:
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
